spring:
  # MySQL 연결 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  data:
    # MongoDB 연결 정보
    mongodb:
      uri: ${PROD_MONGO_URL}
    # Redis 연결 정보
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      password: ${PROD_REDIS_PASSWORD}
  # RabbitMQ 연결 정보
  rabbitmq:
    host: ${PROD_RABBITMQ_HOST}
    port: ${PROD_RABBITMQ_PORT}
    username: ${PROD_RABBITMQ_USERNAME}
    password: ${PROD_RABBITMQ_PASSWORD}

# RabbitMQ queue, exchange, routing-key 정보
rabbitmq:
  queue.name: ${PROD_RABBITMQ_QUEUE_NAME}
  exchange.name: ${PROD_RABBITMQ_EXCHANGE_NAME}
  routing.key: ${PROD_RABBITMQ_ROUTING_KEY}

# 블록체인 네트워크 자동 배포 URL
vote-session:
  deploy:
    url: ${VOTE_SESSION_DEPLOY_URL}
