spring:
  profiles:
    include: jwt
    active: ${SPRING_ACTIVE_PROFILE:dev}
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import: optional:file:.env[.properties]
kakao:
  user-info-url: ${KAKAO_USER_INFO_URL}
mm-logger:
  base-url: ${MM_LOGGER}
logging:
  level:
    com.ssafy.pickit: DEBUG