version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis_boot"
    hostname: "redis"
    environment:
      - REDIS_PASSWORD=rlagudals3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: "mysql:latest"
    container_name: "mysql_boot"
    hostname: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "pickit_db"
      MYSQL_USER: "fkgnssla"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: "mongo:latest"
    container_name: "mongo_boot"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  redis_data:
  mysql_data:
  mongo-data:

