server:
  port: 8761
spring:
  application:
    name: pickit-eureka

eureka:
  client:
    register-with-eureka: false #eureka server? registry? ???? ??
    fetch-registry: false       #registry? ?? ???? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka
