server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEV_EUREKA_SERVICE_URL}


spring:
  application:
    name: pickit-gateway-service
  profiles:
    include: jwt
  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter #Global Filter
          args:
            baseMessage: Spring Cloud Gateway Authentication Filter
            preLogger: true
            postLogger: true
      routes:
        - id: pickit-core-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/** # endpoint
            - Method=GET,POST,PUT,DELETE
