server:
  port: 8000

eureka:
  client:
    register-with-eureka: true # eureka server? registry? ???? ??
    fetch-registry: true       # registry? ?? ???? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: pickit-gateway-service
  cloud:
    gateway:
      routes:
        - id: pickit-core-service 
          uri: http://localhost:8080/
          predicates:
            - Path=/api/** # ?????
            - Method=GET,POST,PUT,DELETE # ?? HTTP ???? ??
#          filters:
#            - RewritePath=/api/temp-vote-session/(?<segment>.*), /$\{segment}
#            - RemoveRequestHeader=Cookie # ?? ?? ??
#            - AuthorizationHeaderFilter # ??? ?? ???