spring:
  data:
    # MongoDB 연결 정보
    mongodb:
      uri: ${PROD_MONGO_URL}
      database: ${PROD_MONGO_DATABASE}
  # Kafka 연결 정보
  kafka:
    bootstrap-servers: ${PROD_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${PROD_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: 'com.ssafy.pickit.domain.vote.dto,com.ssafy.vote.dto,java.util,java.lang'
    topic:
      vote-topic: ${PROD_KAFKA_TOPIC_NAME}