spring:
  profiles:
    include: jwt
    active: ${DEV_ACTIVE_PROFILE}
  mvc:
    servlet:
      path: /api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
kakao:
  user-info-url: ${KAKAO_USER_INFO_URL}