spring:
  # MySQL 연결 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  data:
    # MongoDB 연결 정보
    mongodb:
      uri: ${DEV_MONGO_URL}
      database: ${DEV_MONGO_DATABASE}