server:
  port: 8082
spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  config:
    import: optional:file:.env[.properties]
web3j:
  client-address: ${BLOCKCHAIN_NETWORK}
  private-key: {MNEMONIC}